name: "CI/CD"

on: [push]

jobs:

  # Runs the CI build on all PRs and branches.
  # Publishes to Maven Central on pushes to the "release" branch.
  build:
    runs-on: ubuntu-20.04
    steps:

    - name: "Checkout sources"
      uses: actions/checkout@v2

    - name: "Setup Java"
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: ossrh
        server-username: OSSRH_USERNAME
        server-password: OSSRH_PASSWORD
        gpg-passphrase: GPG_PASSPHRASE
        gpg-private-key: ${{ secrets.OSSRH_GPG_SECRET_KEY }}

    - name: "Setup cache"
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-maven-

    - name: "Run Maven build"
      run: ./mvnw -B package

    - name: "Publish to the Maven Central Repository"
      if: github.ref == 'refs/heads/release'
      run: |
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"

        ./mvnw -B release:prepare release:perform -Dusername=$GITHUB_ACTOR -Dpassword=$GITHUB_TOKEN
      env:
        OSSRH_USERNAME: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
